---
- name: Instalacja aplikacji na Windows przez SSH (winget)
  hosts: windows_ssh
  gather_facts: no

  tasks:
    - name: Zainstaluj OpenVPN Connect
      win_command: winget install -e --id OpenVPNTechnologies.OpenVPNConnect --accept-package-agreements --accept-source-agreements
      register: openvpn_output
      ignore_errors: yes

    - name: Pokaż wynik instalacji OpenVPN Connect
      debug:
        var: openvpn_output.stdout_lines

    - name: Zainstaluj Notepad++
      win_command: winget install -e --id Notepad++.Notepad++ --accept-package-agreements --accept-source-agreements
      register: notepadpp_output
      ignore_errors: yes

    - name: Pokaż wynik instalacji Notepad++
      debug:
        var: notepadpp_output.stdout_lines
